all:
  children:
    springbox_server_1:
      hosts:
        server_1:
          ansible_host: 185.185.68.174
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible
    service:
      children:
        springbox_server_1: {}