name: Deploy Bot
on:
  release:
    types:
      - created
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: maven
      - name: Build with Maven
        run: mvn -B -Drevision=${GITHUB_REF##*/} package
      - uses: actions/upload-artifact@v3
        with:
          name: discord-dnd-bot.jar
          path: target/discord-dnd-bot.jar
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.14.1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          name: ansible
          known_hosts: ${{ secrets.ANSIBLE_SSH_KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Set ansible vault key and inventory
        env:
          ANSIBLE_VAULT_KEY: ${{ secrets.ANSIBLE_VAULT_KEY }}
          ANSIBLE_INVENTORY: ${{ env.ANSIBLE_INVENTORY }}
        run: |
          echo "$ANSIBLE_VAULT_KEY" > .ansible_vault_key
          chmod 600 .ansible_vault_key
          echo "$ANSIBLE_INVENTORY" > ansible_inventory.yml
      - uses: actions/download-artifact@v3
        with:
          name: discord-dnd-bot.jar
          path: ansible/roles/service/files/
      - run: ansible-playbook ansible/setup_server.yml -i ansible_inventory.yml --vault-password-file .ansible_vault_key
